name: Github pages deploy

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 14.x

      - name: Run deploy script
        run: |
          ls
          pwd
