name: Github pages deploy

on:
  push:
    branches: 
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version:  14.x

      - name: Run deploy script
        run: |
          git config user.name "wilfredinni" && git config user.email "carlos.w.montecinos@gmail.com"
          cd website
          npm install
          npm run generate
          npm run deploy     
